### ISSUE TITLE
Inject an Environment Variable that indicates the retry count

### ISSUE THREAD

**Issue by st0le** [dbohdan/recur#1]
Inject an Environment Variable that indicates the retry count, maybe one for the max count too?

$RETRY_COUNT or $COUNT

This lets the script or command printout the attempt number or choose different options based on the count.

**Comment by dbohdan** [comment]
Good idea.

Is `RETRY` an established convention that something else uses? If it isn't, it makes sense to choose an environment variable name that matches the [condition variable](https://github.com/dbohdan/recur?tab=readme-ov-file#conditions) `attempt`. It is also probably best to "namespace" the variable with a unique prefix. That way it won't override a variable the user might want from the environment.

What would you say to `RECUR_ATTEMPT`? I could also pass `RECUR_MAX_ATTEMPTS` to the command.

**Comment by dbohdan** [comment]
I have implemented this in 3f134ca3944c10000ecd4fba9cb2536f148a14cb. Could you try it?
